### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by amorriscode** [amorriscode/terminal-hero#6]
This README is auto generated. Make it suck less.

**Comment by amorriscode** [comment]
See #8 for some Linux installation requirements that we likely want to mention.

**Comment by hyshka** [comment]
See also: https://github.com/amorriscode/terminal-hero/pull/1#issuecomment-612996945 for linux requirements

**Comment by amorriscode** [comment]
I made the `README` a little better when we switched to python.

@hyshka can you confirm if those previous comments are still valid?

If not, I think we can close this issue for now.
